project:
  type: website

website:
  title: "ISSS608 Visual Analytics Coursework"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 0"
          href: hands-On Exe00/hands-On Exe00.html
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise1"
    - text: "Take-home Exercise" 
      menu:
        - text: "Take-home Exercise1"
    
right:
  - href: index.qmd
    text: Home
  - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

